<main>
    <h1>Menu Principal - Minecraft</h1>
        <div class="inner-menu">
            <h2>CADASTROS</h2>
            <a href="/cadastro_bloco">Cadastrar Bloco</a>
            <a href="/cadastro_receita">Cadastrar Receita</a>
            <h2>LISTAGENS</h2>
            <a href="/listar_bloco">Listar Blocos</a>
            <a href="/listar_receita">Listar Receita</a>
        </div>
    </form>
</main>