<main>
    <h1>Menu Principal - Minecraft</h1>
        <div class="inner-menu">
            <h2>CADASTROS</h2>
            <a class="link-button" href="/cadastro_bloco">Cadastrar Bloco</a>
            <a class="link-button" href="/cadastro_receita">Cadastrar Receita</a>
            <h2>LISTAGENS</h2>
            <a class="link-button" href="/listar_bloco">Listar Blocos</a>
            <a class="link-button" href="/listar_receita">Listar Receita</a>
            <a class="link-button" href="/consulta_dados">Consultar API</a>
            <h2>SESSÃO</h2>
            <a class="link-button" href="/logout">Logout</a>
        </div>
    </form>
    <?php if($this->view->cadastro == 'sucesso') { ?>
        <span class="success">*Cadastro realizado com sucesso</span>
    <?php } ?>
    <?php if($this->view->cadastro == 'bloco') { ?>
        <span class="error">O nome do bloco não existe ou foi digitado incorretamente</span>
    <?php } ?>
</main>