<main class="flex-center">
    <h1>Login de Acesso</h1>
    <form action="/autenticar" method="post">
        <div class="form-field">
            <label for="email" >Login do Jogador:</label>
            <input type="email" id="email" name="email">
        </div>
        <div class="form-field">
            <label for="senha">Senha:</label>
            <input type="password" id="senha" name="senha">
        </div>
        <div class="flex-center">
            <button type="submit">Entrar</button>
            <a class="link-button" class="inner-menu" href="/inscreverse">Inscrever-se</a>
        </div>

        <?php if(isset($this->view->login) && $this->view->login == 'erro') { ?>
            <span class="error">*E-mail e ou senha inválido(s)</span>
        <?php } ?>

    </form>
</main>