<main>
    <h1>Inscreva-se</h1>
    <form action="/registrar" method="post">
        <div class="form-field">
            <label for="email" >Email:</label>
            <input type="email" id="email" name="email" value="<?= $this->view->usuario['email']?>">
        </div>
        <div class="form-field">
            <label for="senha">Senha:</label>
            <input type="password" id="senha" name="senha" value="<?= $this->view->usuario['senha']?>">
        </div>
        <div class="flex-center">
            <button type="submit">Inscrever-se</button>
            <a class="link-button" class="inner-menu" href="/">Voltar</a>
        </div>
    </form>
    <?php if($this->view->erroCadastro == 1) { ?>
        <span class="error">*Mínimo de 3 caracteres.</span>
    <?php } ?>
    <?php if($this->view->erroCadastro == 2) { ?>
        <span class="error">*Email já cadastrado.</span>
    <?php } ?>
</main>