<html>
    <head>
        <meta charset="utf-8" />
        <title>Minecraft - Login</title>

        <link rel="stylesheet" type="text/css" href="/css/reset.css">
        <link rel="stylesheet" type="text/css" href="/css/main.css">
        <link rel="stylesheet" type="text/css" href="/css/login.css">
        <link rel="stylesheet" type="text/css" href="/css/menu.css">
        <link rel="stylesheet" type="text/css" href="/css/cadastro.css">
        <link rel="stylesheet" type="text/css" href="/css/listagem.css">
        <link rel="stylesheet" type="text/css" href="/css/sprites.css">

    </head>

    <body>
        <?= $this->content() ?>
    </body>

</html>